### ISSUE TITLE
Notification banner not appearing

### ISSUE THREAD

**Issue by bretonics** [ekonstantinidis/gitify#162] opened 2016-04-23 16:08 UTC
When I get a notification, the email usually comes in first so I immediately look at Gitify to see if there's a new one, however, it takes a little longer (that's ok) but...

What I've noticed is that while I wait the 60 seconds for the new notification to come in, the icon turns green but the OS X alert banner never made a notification alert. Yet checking the Notifications Center, the Gitify notification is actually there.
![2016-04-23 at 12 03 pm](https://cloud.githubusercontent.com/assets/3980538/14762556/5ffad5f2-094b-11e6-8fcb-0163908d77a5.png)
 I have checked that the Notifications Center settings are right for Gitify, and they are; it's set to display a banner and show notifications.

**Comment by ekonstantinidis** [comment] 2016-04-29 09:31
Hello @bretonics! While I'm currently rewriting the app, I did lots of tests with the notifications and I cannot reproduce this issue. Something that might help you - is your mac in the "Do not disturb mode"? If yes, then that should be it! 

<img width="326" alt="screen shot 2016-04-29 at 10 28 23" src="https://cloud.githubusercontent.com/assets/6333409/14912649/8cc35d4e-0df5-11e6-9ff6-447972e641bd.png">

**Comment by ekonstantinidis** [comment] 2016-05-13 13:09
Closing this one for now.

Ps. New version coming soon!

**Closed by ekonstantinidis** 2016-05-13 13:09 UTC
Labels: question
